#!/usr/bin/env python3
# -*- mode: python; python-indent-offset: 4 -*-
#
#   Copyright ©︎2022-2025 AIKAWA Shigechika
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from looseversion import LooseVersion
from jnpr.junos import Device
from jnpr.junos.exception import (
    ConnectAuthError,
    ConnectClosedError,
    ConnectError,
    ConnectRefusedError,
    ConnectTimeoutError,
    ConnectUnknownHostError,
)
from jnpr.junos.exception import RpcError, RpcTimeoutError
from jnpr.junos.utils.config import Config
from jnpr.junos.utils.fs import FS
from jnpr.junos.utils.sw import SW
from lxml import etree
from ncclient.operations.errors import TimeoutExpiredError
from pprint import pprint
import argparse
import configparser
import datetime
import re
import sys
from logging import getLogger, config
import logging

config.fileConfig("logging.ini")
logger = logging.getLogger(__name__)

config = None
args = None
version = "0.1"


def read_config():
    global config
    config = configparser.ConfigParser(allow_no_value=True)
    config.read(args.recipe)
    if len(config.sections()) == 0:
        print(args.recipe, "is empty")
        return True
    for section in config.sections():
        if config.has_option(section, "host"):
            host = config.get(section, "host")
        else:
            host = None
        if host is None:
            # host is [section] name
            config.set(section, "host", section)
        if args.debug:
            for key in config[section]:
                print(section, ">", key, ":", config[section][key])
            print()
    return False


def connect(hostname):
    if args.debug:
        print("connect: start")
    dev = Device(
        host=config.get(hostname, "host"),
        port=int(config.get(hostname, "port")),
        user=config.get(hostname, "id"),
        passwd=config.get(hostname, "pw"),
        ssh_private_key_file=config.get(hostname, "sshkey"),
    )
    err = None
    try:
        dev.open()
        err = False
    except ConnectAuthError as e:
        print("Authentication credentials fail to login: {0}".format(e))
        dev = None
        err = True
    except ConnectRefusedError as e:
        print("NETCONF Connection refused: {0}".format(e))
        dev = None
        err = True
    except ConnectTimeoutError as e:
        print("Connection timeout: {0}".format(e))
        dev = None
        err = True
    except ConnectError as e:
        print("Cannot connect to device: {0}".format(e))
        dev = None
        err = True
    except ConnectUnknownHostError as e:
        print("Unknown Host: {0}".format(e))
        dev = None
        err = True
    except Exception as e:
        print(e)
        dev = None
        err = True
    if args.debug:
        print("connect: err=", err, "dev=", dev)
    if args.debug:
        print("connect: end")
    return err, dev


def copy(hostname, dev):
    if args.debug:
        print("copy: start")
    if args.force:
        if args.debug:
            print("copy: force copy")
    else:
        if check_running_package(hostname, dev):
            print("Already Running, COPY Skip.")
            return False
        if check_remote_package(hostname, dev):
            print("remote package is already copied successfully")
            return False

    # request-system-storage-cleanup
    if args.dryrun:
        print("dryrun: request system storage cleanup")
    else:
        try:
            rpc = dev.rpc.request_system_storage_cleanup(
                no_confirm=True, dev_timeout=60
            )
            # default dev_timeout is 30 seconds, but it's not enough QFX series.
            str = etree.tostring(rpc, encoding="unicode")
            if args.debug:
                print("copy: request-system-storage-cleanup=", str)
            if str.find("<success/>") >= 0:
                print("copy: system storage cleanup successful")
            else:
                print("copy: system storage cleanup failed")
                return True
        except RpcError as e:
            print("system storage cleanup failure caused by RpcError:", e)
            return True
        except RpcTimeoutError as e:
            print("system storage cleanup failure caused by RpcTimeoutError:", e)
            return True
        except Exception as e:
            print(e)
            return True

    # copy
    if args.dryrun:
        print(
            "dryrun: scp(checksum:%s) %s %s:%s"
            % (
                config.get(hostname, "hashalgo"),
                get_model_file(hostname, dev.facts["model"]),
                hostname,
                config.get(hostname, "rpath"),
            )
        )
        ret = False
    else:
        try:
            sw = SW(dev)
            result = sw.safe_copy(
                get_model_file(hostname, dev.facts["model"]),
                remote_path=config.get(hostname, "rpath"),
                progress=True,
                cleanfs=True,
                cleanfs_timeout=300,  # default 300
                checksum=get_model_hash(hostname, dev.facts["model"]),
                checksum_timeout=1200,  # default 300
                checksum_algorithm=config.get(hostname, "hashalgo"),
                force_copy=args.force,
            )
            if result:
                if args.debug:
                    print("copy: successful")
                ret = False
            else:
                if args.debug:
                    print("copy: failed")
                ret = True
        except TimeoutExpiredError as e:
            print("Copy failure caused by TimeoutExpiredError:", e)
            ret = True
        except RpcTimeoutError as e:
            print("Copy failure caused by RpcTimeoutError:", e)
            return True
        except Exception as e:
            print(e)
            ret = True

    if args.debug:
        print("copy: end", ret)
    return ret


def rollback(hostname, dev):
    if args.dryrun:
        print("dryrun: request system software rollback")
    else:
        try:
            rpc = dev.rpc.request_package_rollback({"format": "text"}, dev_timeout=120)
            # default dev_timeout is 30 seconds, but it's not enough SRX4600, MX5 and QFX5110.
            str = etree.tostring(rpc, encoding="unicode")
            if args.debug:
                print("rollback: rpc=", rpc, "str=", str)
            if (
                str.find("Deleting bootstrap installer") >= 0  # MX
                or str.find("NOTICE: The 'pending' set has been removed") >= 0  # EX
                or str.find("will become active at next reboot") >= 0  # SRX3xx
                or str.find("Rollback of staged upgrade succeeded") >= 0  # SRX1500
                or str.find("There is NO image for ROLLBACK") >= 0  # SRX4600
            ):
                print(f"rollback: request system software rollback successful:\n{str}")
            else:
                print(f"rollback: request system software rollback failed:\n{str}")
                return True
        except RpcError as e:
            print("request system software rollback failure caused by RpcError:", e)
            sys.exit(1)
        except RpcTimeoutError as e:
            print(
                "request system software rollback failure caused by RpcTimeoutError:",
                e,
            )
            sys.exit(1)
        except Exception as e:
            print(e)
            sys.exit(1)
    return False


def clear_reboot(dev) -> bool:
    # clear system reboot
    if args.dryrun:
        print("\tdryrun: clear system reboot")
    else:
        try:
            rpc = dev.rpc.clear_reboot({"format": "text"})
            str = etree.tostring(rpc, encoding="unicode")
            logger.debug(f"{rpc=} {str=}")
            if (
                str.find("No shutdown/reboot scheduled.") >= 0
                or str.find("Terminating...") >= 0
            ):
                logger.debug("clear reboot schedule successful")
                print("\tclear reboot schedule successful")
            else:
                logger.debug("clear reboot schedule failed")
                print("\tclear reboot schedule failed")
                return True
        except RpcError as e:
            logger.error(f"Clear reboot failure caused by RpcError: {e}")
            sys.exit(1)
        except RpcTimeoutError as e:
            logger.error(f"Clear reboot failure caused by RpcTimeoutError: {e}")
            sys.exit(1)
        except Exception as e:
            logger.error(e)
            sys.exit(1)
    return False


def install(hostname, dev):
    if args.debug:
        print("install: start")
    if args.force:
        if args.debug:
            print("install: force install")
    else:
        if check_running_package(hostname, dev):
            print("Already Running, INSTALL Skip.")
            return False

    pending = get_pending_version(hostname, dev)
    logger.debug(f"{pending=}")
    if pending is not None:
        planning = get_planning_version(hostname, dev)
        logger.debug(f"{planning=}")
        ret = compare_version(pending, planning)
        logger.debug(f"install: compare_version={ret}")
        if ret == 1:
            logger.debug(f"{pending=} > {planning=} : No need install.")
            print(f"\t{pending=} > {planning=} : No need install.")
        elif ret == -1:
            logger.debug(f"{pending=} < {planning=} : NEED INSTALL.")
            print(f"\t{pending=} < {planning=} : NEED INSTALL.")
        elif ret == 0:
            logger.debug(f"{pending=} = {planning=} : No need install.")
            print(f"\t{pending=} = {planning=} : No need install.")

        if ret == 1 or ret == 0:
            if args.force:
                # force INSTALL
                pass
            else:
                return False

        ret = rollback(hostname, dev)
        if ret:
            if args.force:
                pass
            else:
                return True

    # EX series delete remote package after installed. so, must check first pending version before copy.
    if args.dryrun and (args.copy or args.update):
        print("dryrun: skip remote package check")
    elif check_remote_package(hostname, dev) is not True and args.install:
        # install() does not copy
        logger.info("remote package file not found. Please consider --copy before --install")
        return True

    if copy(hostname, dev):
        return True

    if clear_reboot(dev):
        return True

    # request system configuration rescue save
    if args.dryrun:
        print("dryrun: request system configuration rescue save")
    else:
        cu = Config(dev)
        try:
            ret = cu.rescue("save")
            if ret:
                print("install: rescue config save successful")
            else:
                print("install: rescue config save failed")
                return True
        except ValueError as e:
            print("wrong rescue action", e)
            sys.exit(1)
        except Exception as e:
            print(e)
            sys.exit(1)

    # request system software add ...
    if args.dryrun:
        print(
            "dryrun: request system software add %s/%s"
            % (
                config.get(hostname, "rpath"),
                get_model_file(hostname, dev.facts["model"]),
            )
        )
        ret = False
    else:
        sw = SW(dev)
        status, msg = sw.install(
            get_model_file(hostname, dev.facts["model"]),
            remote_path=config.get(hostname, "rpath"),
            progress=True,
            validate=True,
            cleanfs=True,
            no_copy=True,
            issu=False,
            nssu=False,
            timeout=2400,  # default 1800
            cleanfs_timeout=300,  # default 300
            checksum=get_model_hash(hostname, dev.facts["model"]),
            checksum_timeout=1200,  # default 300
            checksum_algorithm=config.get(hostname, "hashalgo"),
            force_copy=args.force,
            all_re=True,
        )
        del sw
        logger.debug(f"{msg=}")
        if status:
            logger.info("install successful")
            ret = False
        else:
            logger.info("install failed")
            ret = True

    logger.debug(f"end {ret=}")
    return ret


def get_model_file(hostname, model):
    try:
        return config.get(hostname, model.lower() + ".file")
    except Exception as e:
        print(config.read(args.recipe), e)
        sys.exit(1)


def get_model_hash(hostname, model):
    try:
        return config.get(hostname, model.lower() + ".hash")
    except Exception as e:
        print(config.read(args.recipe), e)
        sys.exit(1)


def get_hashcache(hostname, file):
    if config.has_section(hostname) is False:
        return None
    if config.has_option(hostname, file + "hashcache"):
        hashcache = config.get(hostname, file + "hashcache")
    else:
        hashcache = None
    return hashcache


def set_hashcache(hostname, file, value):
    global config
    if config.has_section(hostname) is False:
        # "localhost"
        config.add_section(hostname)
    config.set(hostname, file + "hashcache", value)


def check_local_package(hostname, dev):
    """check local package
    :returns:
       * ``True`` file found, checksum correct.
       * ``False`` file found, checksum incorrect.
       * ``None`` file not found.
    """
    # local package check
    # model, file, hash, algo
    model = dev.facts["model"]
    file = get_model_file(hostname, model)
    hash = get_model_hash(hostname, model)
    if len(file) == 0 or len(hash) == 0:
        return None
    algo = config.get(hostname, "hashalgo")
    sw = SW(dev)
    if get_hashcache("localhost", file) == hash:
        print(f"  - local package: {file} is found. checksum(cache) is OK.")
        return True
    ret = None
    try:
        val = sw.local_checksum(file, algorithm=algo)
        if val == hash:
            print(f"  - local package: {file} is found. checksum is OK.")
            set_hashcache("localhost", file, val)
            ret = True
        else:
            print(f"  - local package: {file} is found. checksum is BAD. COPY AGAIN!")
            ret = False
    except FileNotFoundError as e:
        print(f"  - local package: {file} is not found.")
        logger.debug(e)
    except Exception as e:
        logger.error(e)
    del sw
    return ret


def check_remote_package(hostname, dev):
    """check remote package
    :returns:
       * ``True`` file found, checksum correct.
       * ``False`` file found, checksum incorrect.
       * ``None`` file not found.
    """
    # remote package check
    # model, file, hash, algo
    model = dev.facts["model"]
    file = get_model_file(hostname, model)
    hash = get_model_hash(hostname, model)
    if len(file) == 0 or len(hash) == 0:
        return None
    algo = config.get(hostname, "hashalgo")
    sw = SW(dev)
    ret = None
    if get_hashcache(hostname, file) == hash:
        print(f"  - remote package: {file} is found. checksum(cache) is OK.")
        return True
    try:
        val = sw.remote_checksum(
            config.get(hostname, "rpath") + "/" + file, algorithm=algo
        )
        if val is None:
            print(f"  - remote package: {file} is not found.")
        elif val == hash:
            print(f"  - remote package: {file} is found. checksum is OK.")
            set_hashcache(hostname, file, val)
            ret = True
        else:
            print(f"  - remote package: {file} is found. checksum is BAD. COPY AGAIN!")
            ret = False
    except RpcError as e:
        logger.error("Unable to remote checksum: {0}".format(e))
    except Exception as e:
        logger.error(e)
    del sw
    return ret


def list_remote_path(hostname, dev):
    # list remote path
    if args.debug:
        print("list_remote_path: start")
    # file list /var/tmp/
    fs = FS(dev)
    rpath = config.get(hostname, "rpath")
    dict = fs.ls(path=rpath, brief=False)
    print(dict.get("path") + ":")
    a = dict.get("files")
    if args.list_format == "short":
        for i in a.keys():
            b = a.get(i)
            if b.get("type") == "file":
                print(b.get("path"))
            else:
                print(b.get("path") + "/")
    else:
        for i in a.keys():
            b = a.get(i)
            print(
                "%s %s %9d %s %s"
                % (
                    b.get("permissions_text"),
                    b.get("owner"),
                    b.get("size"),
                    b.get("ts_date"),
                    b.get("path"),
                )
            )
        print("total files: %d" % dict.get("file_count"))
    if args.debug:
        print("list_remote_path: end")
    return dict


def dryrun(hostname, dev):
    if args.debug:
        print("dryrun: start")
        print("hostname: ", dev.facts["hostname"])
        print("model: ", dev.facts["model"])
        print("file:", get_model_file(hostname, dev.facts["model"]))
        print("hash:", get_model_hash(hostname, dev.facts["model"]))
        print("algo:", config.get(hostname, "hashalgo"))
    # show hostname, model, file, hash and algo
    # local package check
    local = check_local_package(hostname, dev)
    # remote package check
    remote = check_remote_package(hostname, dev)
    if args.debug:
        print("dryrun: end")
    if local and remote:
        return True
    else:
        return False


def check_running_package(hostname, dev):
    """compare running version with planning version
    :returns:
       * ``True`` same(correct)
       * ``False`` diffrent(incorrect)
    """
    if args.debug:
        print("check_running_package: start")
    ret = None
    ver = dev.facts["version"]
    rever = re.sub(r"\.", r"\\.", ver)
    if args.debug:
        print("check_running_package: ver", ver)
        print("check_running_package: rever", rever)
    m = re.search(rever, get_model_file(hostname, dev.facts["model"]))
    if args.debug:
        print("check_running_package: m", m)
    if m is None:
        # unmatch(different version)
        ret = False
    else:
        # match(same version)
        ret = True
    if args.debug:
        print("check_running_package: end")
    return ret


def compare_version(left: str, right: str) -> int | None:
    """compare version left and right

    :param left: version left string, ex 18.4R3-S9.2
    :param right: version right string, ex 18.4R3-S10

    :return:  1 if left  > right
              0 if left == right
             -1 if left  < right
    """
    if args.debug:
        print(f"compare_version: left={left}, right={right}.")
    if left is None or right is None:
        return None
    if LooseVersion(left.replace("-S", "00")) > LooseVersion(right.replace("-S", "00")):
        return 1
    if LooseVersion(left.replace("-S", "00")) < LooseVersion(right.replace("-S", "00")):
        return -1
    return 0


def get_pending_version(hostname, dev) -> str:
    """
    :returns:
       * ``None`` not exist
       * ``str`` pending version string
    """
    pending = None
    try:
        rpc = dev.rpc.get_software_information({"format": "text"})
        str = etree.tostring(rpc, encoding="unicode")
        if args.debug:
            print(
                "get_pending_version: rpc=", rpc, "type(str)=", type(str), "str=", str
            )
        if dev.facts["personality"] == "SWITCH":
            if args.debug:
                print("get_pending_version: EX/QFX series")
            # Pending: 18.4R3-S10
            m = re.search(r"^Pending:\s(.*)$", str, re.MULTILINE)
            if m is not None:
                pending = m.group(1)
        elif dev.facts["personality"] == "MX":
            if args.debug:
                print("get_pending_version: MX series")
            # JUNOS Installation Software [18.4R3-S10]
            m = re.search(
                r"^JUNOS\sInstallation\sSoftware\s\[(.*)\]$", str, re.MULTILINE
            )
            if m is not None:
                pending = m.group(1)
        elif dev.facts["personality"] == "SRX_BRANCH":
            # Dual Partition - SRX300, SRX345
            if args.debug:
                print("get_pending_version: SRX_BRANCH series")
            xml = dev.rpc.get_snapshot_information(media="internal")
            if args.debug:
                print(f"get_snapshot_information: xml={etree.dump(xml)}")
            primary = False
            for i in range(len(xml)):
                if args.debug:
                    print(
                        f"get_snapshot_information: i={i}, tag={xml[i].tag}, text={xml[i].text}"
                    )
                if (
                    xml[i].tag == "snapshot-medium"
                    and re.match(".*primary", xml[i].text, re.MULTILINE | re.DOTALL)
                    is not None
                ):
                    if args.debug:
                        print("primary find")
                    primary = True
                if (
                    primary
                    and xml[i].tag == "software-version"
                    and xml[i][0].tag == "package"
                    and xml[i][0][1].tag == "package-version"
                ):
                    pending = xml[i][0][1].text.strip()
                    break
        elif (
            dev.facts["personality"] == "SRX_MIDRANGE"
            or dev.facts["personality"] == "SRX_HIGHEND"
        ):
            # SRX1500, SRX4600
            if args.debug:
                print("get_pending_version: SRX_MIDRANGE or SRX_HIGHEND series")
            # show log install
            # upgrade_platform: Staging of /var/tmp/junos-srxentedge-x86-64-20.4R3.8-linux.tgz completed
            # &lt;package-result&gt;0&lt;/package-result&gt;
            try:
                rpc = dev.rpc.get_log({"format": "text"}, filename="install")
                str = etree.tostring(rpc, encoding="unicode")
                if args.debug:
                    print(
                        "get_pending_version: rpc=",
                        rpc,
                        "type(str)=",
                        type(str),
                        "str=",
                        str,
                    )
                if str is not None:
                    # search from last <output> block
                    start = str.rfind("&lt;output&gt;")
                    m = re.search(
                        r"upgrade_platform: Staging of /var/tmp/.*-(\d{2}\.\d.*\d).*\.tgz completed",
                        str[start:],
                        re.MULTILINE,
                    )
                    if m is not None:
                        pending = m.group(1).strip()
                    m = re.search(
                        r"&lt;package-result&gt;(\d)&lt;/package-result&gt;",
                        str[start:],
                        re.MULTILINE,
                    )
                    if m is not None:
                        if int(m.group(1)) == 0:
                            pass
                        else:
                            pending = None
            except Exception as e:
                print(e)
                sys.exit(1)
        else:
            print("Unknown personality:", dev.facts)
            return True
    except RpcError as e:
        print("Show version failure caused by RpcError:", e)
        sys.exit(1)
    except RpcTimeoutError as e:
        print("Show version failure caused by RpcTimeoutError:", e)
        sys.exit(1)
    except Exception as e:
        print(e)
        sys.exit(1)
    return pending


def get_planning_version(hostname, dev) -> str:
    planning = None
    f = get_model_file(hostname, dev.facts["model"])
    m = re.search(r".*-(\d{2}\.\d.*\d).*\.tgz", f)
    if m is not None:
        planning = m.group(1).strip()
    else:
        logger.debug("get_planning_version: planning version is not found")
    return planning


def get_reboot_information(hostname, dev):
    """show system reboot
    :return: halt requested by exadmin at Sun Dec 19 08:30:00 2021
             shutdown requested by exadmin at Sun Dec 12 08:30:00 2021
             reboot requested by exadmin at Sun Dec  5 01:00:00 2021
             No shutdown/reboot scheduled.
    """
    try:
        rpc = dev.rpc.get_reboot_information({"format": "text"})
    except RpcError as e:
        logger.error("Show version failure caused by RpcError:", e)
        sys.exit(1)
    except RpcTimeoutError as e:
        logger.error("Show version failure caused by RpcTimeoutError:", e)
        sys.exit(1)
    except Exception as e:
        logger.error(e)
        sys.exit(1)
    str = etree.tostring(rpc, encoding="unicode")
    if args.debug:
        print(str)
    m = re.search(
        r"((halt|shutdown|reboot)\srequested\sby\s.*\sat\s(.*\d)|No\sshutdown\/reboot\sscheduled\.)",
        str,
        re.MULTILINE,
    )
    if m is None:
        return None
    return m.group(1)


def show_version(hostname, dev):
    """show version
    show running version
    show pending version
    check for updated
    suggest action to copy, install, reboot or beer.
    """

    logger.debug("start")

    print("  - hostname:", dev.facts["hostname"])
    print("  - model:", dev.facts["model"])
    running = dev.facts["version"]
    print("  - running version:", running)

    # compare with planning version
    planning = get_planning_version(hostname, dev)
    print("  - planning version:", planning)
    ret = compare_version(running, planning)
    if ret == 1:
        print(f"    - {running=} > {planning=}")
    elif ret == -1:
        print(f"    - {running=} < {planning=}")
    elif ret == 0:
        print(f"    - {running=} = {planning=}")
    # compare with pending version
    pending = get_pending_version(hostname, dev)
    print("  - pending version:", pending)
    ret = compare_version(running, pending)
    if ret == 1:
        print(f"    - {running=} > {pending=} : Do you want to rollback?")
    elif ret == -1:
        print(f"    - {running=} < {pending=} : Please plan to reboot.")
    elif ret == 0:
        print(f"    - {running=} = {pending=}")

    # local package check
    local = check_local_package(hostname, dev)

    # remote package check
    remote = check_remote_package(hostname, dev)

    rebooting = get_reboot_information(hostname, dev)
    if rebooting is not None:
        print(f"  - {rebooting}")

    logger.debug("end")

    return False


def reboot(hostname: str, dev, reboot_dt: datetime.datetime):
    logger.debug(f"{reboot_dt=}")
    try:
        rpc = dev.rpc.get_reboot_information({"format": "text"})
    except ConnectError as err:
        logger.error(f"{err=}")
        return 2
    str = etree.tostring(rpc, encoding="unicode")
    logger.debug(f"{str=}")
    if str.find("No shutdown/reboot scheduled.") >= 0:
        pass
    else:
        logger.debug("ANY SHUTDWON/REBOOT SCHEDULE EXISTS")
        match = re.search(r"^(\w+) requested by (\w+) at (.*)$", str, re.MULTILINE)
        if len(match.groups()) == 3:
            dt = datetime.datetime.strptime(match.group(3), "%a %b %d %H:%M:%S %Y")
            print(f"\t{match.group(1).upper()} SCHEDULE EXISTS AT {dt}")
            if args.force:
                logger.debug("force clear reboot")
                print("\tforce: clear reboot")
                if clear_reboot(dev):
                    return 3
            else:
                logger.debug("skip clear reboot")
    # reboot
    at_str = reboot_dt.strftime("%y%m%d%H%M")
    sw = SW(dev)
    try:
        if args.dryrun:
            msg = f"dryrun: reboot at {at_str}"
        else:
            msg = sw.reboot(at=at_str)
    except ConnectError as e:
        logger.error(f"{e=}")
        return 4
    except RpcError as e:
        logger.error(f"{e}")
        return 5
    print(f"\t{msg}")
    del sw

    dev.close()
    logger.debug("success")
    return 0


def yymmddhhmm_type(dt_str: str) -> datetime.datetime:
    try:
        return datetime.datetime.strptime(dt_str, "%y%m%d%H%M")
    except ValueError as e:
        raise argparse.ArgumentTypeError(
            f"{e}: {dt_str} must be yymmddhhmm format. ex. 2501020304"
        )


def main():
    parser = argparse.ArgumentParser(
        description="automatically detect Juniper models and automatically update JUNOS packages",
        epilog="default action is show device facts",
    )
    parser.add_argument(
        "specialhosts",
        metavar="hostname",
        type=str,
        nargs="*",
        help="special hostname(s)",
    )
    parser.add_argument(
        "--recipe",
        default="junos.ini",
        type=str,
        help="junos recipe filename (default: %(default)s)",
    )
    parser.add_argument(
        "--list",
        "--short",
        "-ls",
        action="store_const",
        dest="list_format",
        const="short",
        help="short list remote path (like as ls)",
    )
    parser.add_argument(
        "--longlist",
        "-ll",
        action="store_const",
        dest="list_format",
        const="long",
        help="long list remote path (like as ls -l)",
    )
    parser.add_argument(
        "--dryrun",
        action="store_true",
        help="test for --copy/--install/--update. connect and message output. No execute.",
    )
    parser.add_argument(
        "--copy", action="store_true", help="copy package from local to remote"
    )
    parser.add_argument(
        "--install", action="store_true", help="install copied package on remote"
    )
    parser.add_argument(
        "--update",
        "--upgrade",
        action="store_true",
        help="copy(=--copy) and install(=--install)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="force execute copy, install and update",
    )
    parser.add_argument(
        "--showversion",
        "--version",
        action="store_true",
        help="show running/planning/pending version and reboot schedule",
    )
    parser.add_argument(
        "--rollback", action="store_true", help="rollback installed package"
    )
    parser.add_argument(
        "--rebootat",
        default=None,
        type=yymmddhhmm_type,
        help="reboot at Date and Time. format is yymmddhhmm. ex: 2501020304",
    )
    parser.add_argument("-d", "--debug", action="store_true", help="for debug")
    parser.add_argument("-V", action="version", version="%(prog)s " + version)
    global args
    args = parser.parse_args()

    logger.debug("start")

    if read_config():
        print(args.recipe, "is not ready")
        sys.exit(1)

    targets = []
    if len(args.specialhosts) == 0:
        for i in config.sections():
            tmp = config.get(i, "host")
            logger.debug(f"{i=} {tmp=}")
            if tmp is not None:
                targets.append(i)
            else:
                print(i, "is not found in", args.recipe)
                sys.exit(1)
    else:
        for i in args.specialhosts:
            if config.has_section(i):
                tmp = config.get(i, "host")
            else:
                print(i, "is not found in", args.recipe)
                sys.exit(1)
            logger.debug(f"{i=} {tmp=}")
            targets.append(i)

    logger.debug(f"{args=}")
    logger.debug(f"{args.specialhosts=}")
    logger.debug(f"{targets=}")

    for host in targets:
        logger.debug(f"{host=}")
        logger.debug(f"{datetime.datetime.now()=}")
        print(f"# {host}")

        err, dev = connect(host)
        if err or dev is None:
            sys.exit(1)
        if (
            args.list_format is None
            and args.copy is False
            and args.install is False
            and args.update is False
            and args.showversion is False
            and args.rollback is False
            and args.rebootat is None
        ) or args.debug:
            pprint(dev.facts)
        if args.list_format is not None:
            list_remote_path(host, dev)
        # copy or update
        err = None
        if args.copy:
            err = copy(host, dev)
            if err:
                sys.exit(1)
        # rollback
        if args.rollback:
            pending = get_pending_version(host, dev)
            print(f"rollback: pending version is {pending}")
            if pending is None:
                print("rollback: skip")
            else:
                err = rollback(host, dev)
                if err:
                    sys.exit(err)
                else:
                    if args.dryrun is False:
                        print("rollback: successful")
        # install or update
        if args.install or args.update:
            err = install(host, dev)
            if err:
                sys.exit(1)
        # show version
        if args.showversion:
            err = show_version(host, dev)
            if err:
                sys.exit(1)
        # reboot at
        if args.rebootat:
            err = reboot(host, dev, args.rebootat)
            if err:
                sys.exit(err)
        # close
        try:
            dev.close()
        except ConnectClosedError as e:
            print("Connection unexpectedly closed", e)
        except Exception as e:
            print(e)

        print("")

    logger.debug("end")

    return False


if __name__ == "__main__":
    sys.exit(main())
